### ISSUE TITLE
celeba_masks

### ISSUE THREAD

**Issue by zhaoji-1024** [securifai/masked_faces#1]
I can not find celeba_masks

**Comment by raduionescu** [comment]
The download links are in the readme file. The images are not included in the repo due to the large size (~10 Gb). The link for CelebA is: https://fmiunibuc-my.sharepoint.com/:u:/g/personal/radu_ionescu_fmi_unibuc_ro/EQdIsLQB9jdOkaOHV0T_wMQBSz8qQkxRm7w8Nuo_qZOoFA?e=1eekcq

**Comment by zhaoji-1024** [comment]
Thank you for your answer!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月9日(星期四) 下午2:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [securifai/masked_faces] celeba_masks (#1)





 
The download links are in the readme file. The images are not included in the repo due to the large size (~10 Gb). The link for CelebA is: https://fmiunibuc-my.sharepoint.com/:u:/g/personal/radu_ionescu_fmi_unibuc_ro/EQdIsLQB9jdOkaOHV0T_wMQBSz8qQkxRm7w8Nuo_qZOoFA?e=1eekcq
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
